---
- name: Upgrade Fedora 42 to 43 with px-proxy update
  hosts: fedora_hosts
  become: yes
  vars:
    pxproxy_wheels_src: /pxproxy_43
    pxproxy_wheels_dest: /tmp/pxproxy_43
    
  tasks:
    - name: Update all packages to latest versions
      ansible.builtin.dnf:
        name: "*"
        state: latest
        
    - name: Install dnf-plugin-system-upgrade
      ansible.builtin.dnf:
        name: dnf-plugin-system-upgrade
        state: present
        
    - name: Download Fedora 43 packages
      ansible.builtin.command:
        cmd: dnf system-upgrade download --releasever=43 -y
      register: download_result
      changed_when: download_result.rc == 0
      
    - name: Create temporary directory for px-proxy wheels
      ansible.builtin.file:
        path: "{{ pxproxy_wheels_dest }}"
        state: directory
        mode: '0755'
        
    - name: Copy px-proxy wheel files to target machine
      ansible.builtin.copy:
        src: "{{ pxproxy_wheels_src }}/"
        dest: "{{ pxproxy_wheels_dest }}/"
        mode: '0644'
        
    - name: Check if px-proxy is currently installed
      ansible.builtin.command:
        cmd: pip3.13 show px-proxy
      register: pxproxy_check
      failed_when: false
      changed_when: false
      
    - name: Uninstall old px-proxy (Python 3.13 version)
      ansible.builtin.command:
        cmd: pip3.13 uninstall -y px-proxy
      when: pxproxy_check.rc == 0
      
    - name: Perform system upgrade reboot
      ansible.builtin.command:
        cmd: dnf system-upgrade reboot
      async: 1
      poll: 0
      ignore_errors: yes
      
    - name: Wait for system to go down
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 60
      delegate_to: localhost
      become: no
      ignore_errors: yes
      
    - name: Wait for system to come back online (this may take 15-30 minutes)
      ansible.builtin.wait_for_connection:
        delay: 120
        timeout: 1800
        
    - name: Verify Fedora version
      ansible.builtin.command:
        cmd: cat /etc/fedora-release
      register: fedora_version
      changed_when: false
      
    - name: Display Fedora version
      ansible.builtin.debug:
        msg: "{{ fedora_version.stdout }}"
        
    - name: Install px-proxy and dependencies from wheels (Python 3.14)
      ansible.builtin.command:
        cmd: pip3.14 install --no-index --find-links={{ pxproxy_wheels_dest }} px-proxy
      register: pip_install
      changed_when: "'Successfully installed' in pip_install.stdout"
      
    - name: Verify px-proxy installation
      ansible.builtin.command:
        cmd: pip3.14 show px-proxy
      register: pxproxy_verify
      changed_when: false
      
    - name: Display px-proxy installation details
      ansible.builtin.debug:
        msg: "{{ pxproxy_verify.stdout }}"
        
    - name: Clean up temporary wheel directory
      ansible.builtin.file:
        path: "{{ pxproxy_wheels_dest }}"
        state: absent
        
    - name: Clean up old dnf cache
      ansible.builtin.command:
        cmd: dnf clean all
      changed_when: true
