---
- hosts: step_ca_servers
  become: yes
  vars:
    artifactory_url: "https://your-artifactory.company.com"
    step_ca_version: "0.25.0"
    
  tasks:
    - name: Install step-ca from Artifactory
      get_url:
        url: "{{ artifactory_url }}/generic/step-ca/step-ca_{{ step_ca_version }}_linux_amd64.tar.gz"
        dest: /tmp/step-ca.tar.gz
        
    - name: Extract step-ca
      unarchive:
        src: /tmp/step-ca.tar.gz
        dest: /usr/local/bin/
        remote_src: yes
        creates: /usr/local/bin/step-ca
        
    - name: Create step-ca user
      user:
        name: step-ca
        system: yes
        shell: /bin/false
        home: /etc/step-ca
        create_home: yes
        
    - name: Initialize step-ca
      become_user: step-ca
      shell: |
        cd /etc/step-ca
        step ca init \
          --name "Internal ACME CA" \
          --dns "{{ ansible_default_ipv4.address }}" \
          --address ":8443" \
          --provisioner "internal-acme" \
          --acme
      args:
        creates: /etc/step-ca/config/ca.json
        
    - name: Configure step-ca for ACME
      become_user: step-ca
      copy:
        content: |
          {
            "root": "/etc/step-ca/certs/root_ca.crt",
            "federateRoots": [],
            "crt": "/etc/step-ca/certs/intermediate_ca.crt",
            "key": "/etc/step-ca/secrets/intermediate_ca_key",
            "address": ":8443",
            "insecureAddress": "",
            "dnsNames": ["{{ ansible_default_ipv4.address }}"],
            "logger": {"format": "text"},
            "authority": {
              "provisioners": [
                {
                  "type": "ACME",
                  "name": "acme"
                }
              ]
            },
            "tls": {
              "cipherSuites": [
                "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
                "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256"
              ],
              "minVersion": 1.2,
              "maxVersion": 1.3,
              "renegotiation": false
            }
          }
        dest: /etc/step-ca/config/ca.json
        owner: step-ca
        group: step-ca
        mode: '0600'
        
    - name: Create step-ca systemd service
      copy:
        content: |
          [Unit]
          Description=Step Certificate Authority
          Documentation=https://smallstep.com/docs/step-ca
          After=network.target
          
          [Service]
          Type=simple
          User=step-ca
          Group=step-ca
          WorkingDirectory=/etc/step-ca
          ExecStart=/usr/local/bin/step-ca config/ca.json
          Restart=on-failure
          RestartSec=5
          
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/step-ca.service
      notify: 
        - reload systemd
        - start step-ca
        
    - name: Configure firewalld for step-ca
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      with_items:
        - "8443/tcp"  # CA management
        - "9000/tcp"  # ACME server
        
  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: yes
    - name: start step-ca
      systemd:
        name: step-ca
        state: started
        enabled: yes